# src/Cloudy/Bundle/CrudBundle/Resources/config/routing.yml
CloudyCrudBundle_homepage:
    pattern:  /
    defaults: { _controller: CloudyCrudBundle:Page:index }
    requirements:
        _method:  GET
        
CloudyCrudBundle_about:
    pattern:  /about
    defaults: { _controller: CloudyCrudBundle:Page:about }
    requirements:
        _method:  GET
        
CloudyCrudBundle_contact:
    pattern:  /contact
    defaults: { _controller: CloudyCrudBundle:Page:contact }
    requirements:
        _method:  GET|POST

CloudyCrudBundle_plantscalculator:
    pattern:  /plantscalculator
    defaults: { _controller: CloudyCrudBundle:Page:plantsCalculator }
    requirements:
        _method:  GET|POST