# src/Cloudy/Bundle/CrudBundle/Resources/config/routing.yml
CloudyCrudBundle_homepage:
    pattern:  /
    defaults: { _controller: CloudyCrudBundle:Page:index }
    requirements:
        _method:  GET
        
CloudyCrudBundle_about:
    pattern:  /about
    defaults: { _controller: CloudyCrudBundle:Page:about }
    requirements:
        _method:  GET
        
CloudyCrudBundle_contact:
    pattern:  /contact
    defaults: { _controller: CloudyCrudBundle:Page:contact }
    requirements:
        _method:  GET|POST

CloudyCrudBundle_plantscalculator:
    pattern:  /plantscalculator
    defaults: { _controller: CloudyCrudBundle:Page:plantsCalculator }
    requirements:
        _method:  GET|POST

CloudyCrudBundle_dom:
    pattern:  /dom
    defaults: { _controller: CloudyCrudBundle:Page:dom }
    requirements:
        _method:  GET
        
CloudyCrudBundle_cssselector:
    pattern:  /cssselector
    defaults: { _controller: CloudyCrudBundle:Page:cssSelector }
    requirements:
        _method:  GET
        
CloudyCrudBundle_goutte:
    pattern:  /goutte
    defaults: { _controller: CloudyCrudBundle:Page:goutte }
    requirements:
        _method:  GET
        
CloudyCrudBundle_blog_show:
    pattern:  /{id}
    defaults: { _controller: CloudyCrudBundle:Blog:show }
    requirements:
        _method:  GET
        id: \d+

CloudyCrudBundle_comment_create:
    pattern:  /comment/{blog_id}
    defaults: { _controller: CloudyCrudBundle:Comment:create }
    requirements:
        _method:  POST
        blog_id: \d+		