dog:
    resource: "@DogBundle/Resources/config/routing.yml"
    prefix:   /dogs/

cloudy_crud:
    resource: "@CloudyCrudBundle/Resources/config/routing.yml"
    prefix:   /cloudy/

app:
    resource: @AppBundle/Controller/
    type:     annotation
