<?php

namespace Dogs\DogBundle\Entity\Repository;

/**
 * DogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DogRepository extends \Doctrine\ORM\EntityRepository
{
}
