<?php
namespace Dogs\DogBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DogRepository extends \Doctrine\ORM\EntityRepository
{
    public function getListOfDogs()
    {
        $query = $this->createQueryBuilder('d')
                      ->select('d')
                      ->addOrderBy('d.created');
                      
        return $query->getQuery()
                     ->getResult();
    }
    
    public function getListOfDogsFromYesterday($time)
    {
        $query = $this->createQueryBuilder('y')
                      ->select('y')
                      ->where('y.created = :time')
                      ->setParameter('time', $time);
                      
        return $query->getQuery()
                     ->getResult();
    }
}
