dog_add:
    path:     /add
    defaults: { _controller: DogBundle:Main:add }
    
dog_main:
    path:     /
    defaults: { _controller: DogBundle:Main:main }
    
dog_test:
    path:     /test
    defaults: { _controller: DogBundle:Main:test }
